# 관리자 권한 갖기
sudo: required

#언어(플램폿)선택
language: generic

#도커 환경 구성
services:
  - docker

#스크립트를 실행할 수 있는 환경
before_install:
  - echo "start Creating an image with dockerfile"
  - docker build -t dk/docker-react-app -f Dockerfile.dev .

#실행할 스크립트
script:
  - docker run -e CI=true dk/docker-react-app yarn run test -- --coverage


# 배포 관련 설정
deploy:
  edge: true
  provider: elasticbeanstalk
  region: ap-northeast-2
  app: docker-react-app
  env: DockerReactApp-env
  bucket_name: elasticbeanstalk-ap-northeast-2-972153559337
  bucket_path: docker-react-app
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY